//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomenda
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> published { get; set; }
    }
}
